export { MainHeader } from './MainHeader'
export { TourFinder } from './TourFinder'
export { Advantages } from './Advantages'
export { PopularTours } from './PopularTours'
export { FindNoTours } from './FindNoTours'
export { MainFooter } from './MainFooter'
export { RegionList } from './RegionList'
export { ToursList } from './ToursList'
